FROM cgr.dev/chainguard/wolfi-base

ARG BW_CLI_VERSION=2024.2.0

RUN apk add -u bash cronie supervisor curl unzip && \
    curl -L -s -o bw.zip https://github.com/bitwarden/clients/releases/download/cli-v${BW_CLI_VERSION}/bw-linux-${BW_CLI_VERSION}.zip && \
    unzip bw.zip -d /usr/local/bin && \
    rm -rfv *.zip /tmp/* /var/cache/apk/*

ADD fs /

ENTRYPOINT ["supervisord", "--nodaemon", "--configuration", "/etc/supervisord.conf"]
