package:
  name: bitwarden-cli
  version: 2024.2.0
  description: Bitwarden CLI
  epoch: 0
  target-architecture:
  - x86_64

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox

pipeline:
  - uses: fetch
    with:
      expected-sha256: 836e7cccac3711df0d81644a73fa9c6fc97d7681c9b11eff7db2d20d9190f787
      uri: https://github.com/bitwarden/clients/releases/download/cli-v${{package.version}}/bw-linux-${{package.version}}.zip
      extract: false

  - runs: |
      unzip -o bw-linux-${{package.version}}.zip
      install -m755 -D -t "${{targets.destdir}}/usr/bin" bw
    
update:
  enabled: true
  github:
    identifier: bitwarden/clients
    tag-filter: "cli-"
    use-tag: true
